### ISSUE TITLE
using vaadin

### ISSUE THREAD

**Issue by ChrisdeG** [mendix/sassaas-compiler#2]
Hello,

It looks like you use vaadin java sass implementation, but I am not sure. This implementation seems to be outdated and does not support all features Mendix uses. I would like to make a Sass Mendix Module but not as rest service. Is this possible?

Chris de Gelder

**Comment by xiwenc** [comment]
The current code uses Jsass:
- https://github.com/mendix/sassaas-compiler/blob/master/src/main/java/com/mendix/ux/sassaas/SassController.java#L36 
- https://github.com/mendix/sassaas-compiler/blob/master/src/main/java/com/mendix/ux/sassaas/SCSSProcessorJsass.java
- https://github.com/bit3/jsass

We were experimenting (this project is an experiment after all) with Vaadin and Jsass. Hence we had two implementations.

Not sure what you mean by building a Sass Mendix Module but why do you think it is not possible?

**Comment by ChrisdeG** [comment]
Hello Xiwen,

Thanks a lot.

I got problems with using vaadin. It won’t compile Mendix scss. But I will
take a look at jsass.

Kind regards,

[image: FlowFabric] http://www.flowfabric.com/

Chris de Gelder

Business Consultant

cdgelder@flowfabric.com

+31(0)6 - 461 39 865

_Van:_ Xiwen Cheng [mailto:notifications@github.com]
_Verzonden:_ Monday, February 8, 2016 1:28 PM
_Aan:_ mendix/sassaas-compiler
_CC:_ ChrisdeG
_Onderwerp:_ Re: [sassaas-compiler] using vaadin (#2)

The current code uses Jsass:

   -
   https://github.com/mendix/sassaas-compiler/blob/master/src/main/java/com/mendix/ux/sassaas/SassController.java#L36
   -
   https://github.com/mendix/sassaas-compiler/blob/master/src/main/java/com/mendix/ux/sassaas/SCSSProcessorJsass.java
- https://github.com/bit3/jsass

We were experimenting (this project is an experiment after all) with Vaadin
and Jsass. Hence we had two implementations.

Not sure what you mean by building a Sass Mendix Module but why do you
think it is not possible?

—
Reply to this email directly or view it on GitHub
https://github.com/mendix/sassaas-compiler/issues/2#issuecomment-181344482
.[image: Afbeelding verwijderd door afzender.]

**Comment by xiwenc** [comment]
You are welcome!

Closing the issue for now; re-open if needed ;)
